# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2023743449504
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.zeros((10, 10))
print('{0} bytes'.format(Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
Z = np.nonzero([1, 2, 0, 0, 4, 0])
print(Z)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
rg = np.random.default_rng()
rg.random((3, 3, 3))

array([[[0.01234883, 0.26268156, 0.16514956],
        [0.48873685, 0.47503541, 0.79870007],
        [0.23098041, 0.25877114, 0.85531209]],

       [[0.0972295 , 0.24364084, 0.59599042],
        [0.24728944, 0.50684009, 0.21000267],
        [0.68239646, 0.75917232, 0.45031257]],

       [[0.7970537 , 0.59400191, 0.04308672],
        [0.57078268, 0.31317878, 0.0890544 ],
        [0.08442591, 0.32435874, 0.98073511]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
A = np.random.random((10, 10))
print(A.min())
print(A.max())

0.027150800373773598
0.9972283823008543


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
A = np.random.random(30)
print(A.mean())

0.5838720444956766


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
rg = np.random.default_rng()
A = rg.random((5, 5))
padded_A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(padded_A)

[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.70271622 0.75923461 0.61814128 0.62758896 0.27583366
  0.        ]
 [0.         0.65753456 0.84700685 0.85090944 0.66288924 0.10139117
  0.        ]
 [0.         0.02997218 0.6315889  0.74999479 0.7407264  0.8705918
  0.        ]
 [0.         0.37452531 0.12388164 0.40019129 0.47562435 0.52204137
  0.        ]
 [0.         0.00815472 0.96731292 0.40901958 0.96331985 0.9470667
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
Z = np.diag(1 + np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z = np.zeros((8, 8), int)
Z[::2, 1::2] = 1
Z[1::2, ::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
A = np.array([[0, 1],
              [1, 0]])
Z = np.tile(A, (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
Z = np.random.random((5, 5))
NZ = (Z - np.mean(Z)) / np.std(Z)
print(NZ)

[[-0.23468404  0.68980118 -1.44295429  0.92121193  1.18805888]
 [ 0.66533752 -0.7618796  -0.48204534  1.54330626 -1.71574015]
 [ 1.38706064  0.86939602 -1.70516241  0.4316963   1.18221185]
 [-0.4269381  -0.71562847 -0.2846068  -0.70080483  0.85720026]
 [-1.56838014  1.22010332 -0.02991433 -0.31943164 -0.56721406]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([('r', np.ubyte),
                  ('g', np.ubyte),
                  ('b', np.ubyte),
                  ('a', np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
rng = np.random.default_rng()
A = rng.integers(10, size=(3, 2))
B = rng.integers(10, size=(2, 3))
C = A @ B
print(A)
print(B)
print(C)

[[9 4]
 [2 2]
 [7 7]]
[[8 3 9]
 [7 2 5]]
[[100  35 101]
 [ 30  10  28]
 [105  35  98]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
rng = np.random.default_rng()
Z = rng.choice(10, 10)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 2  0  8 -6  0  3 -7  1 -5  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
rng = np.random.default_rng(1)
Z = rng.integers(10, size=10)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z ilegal

[4 5 7 9 0 1 8 9 2 3]
[      256      3125    823543 387420489         1         1  16777216
 387420489         4        27]
[  8  16  64 256   0   1 128 256   2   4]
[False False False False False False False False False False]
[0.+4.j 0.+5.j 0.+7.j 0.+9.j 0.+0.j 0.+1.j 0.+8.j 0.+9.j 0.+2.j 0.+3.j]
[4. 5. 7. 9. 0. 1. 8. 9. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\HP\AppData\Local\Temp\ipykernel_3612\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_3612\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\HP\AppData\Local\Temp\ipykernel_3612\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
rng = np.random.default_rng()
Z = rng.uniform(-10,10,10)
print(Z)
A = np.copysign(np.ceil(np.abs(Z)), Z)
print(A)

[-2.59124189  7.06321488  4.59083314  4.54387918  6.2688864  -4.8139968
  8.25967386 -1.61564534  5.31188974 -5.89832572]
[-3.  8.  5.  5.  7. -5.  9. -2.  6. -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
rng = np.random.default_rng()
A = rng.uniform(-10, 10, size=(2,2))
B = rng.uniform(-10, 10, size=(3,3))
print(np.intersect1d(A, B))

[]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-02-27
2024-02-28
2024-02-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones((3, 3))
B = np.ones((3, 3))*2
np.add(A, B, out=B)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([[-3., -3., -3.],
       [-3., -3., -3.],
       [-3., -3., -3.]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 4. 1. 8. 9. 8. 1. 5. 1. 3.]
[0. 4. 1. 8. 9. 8. 1. 5. 1. 3.]
[0. 4. 1. 8. 9. 8. 1. 5. 1. 3.]
[0 4 1 8 9 8 1 5 1 3]
[0. 4. 1. 8. 9. 8. 1. 5. 1. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
Z = np.zeros((5,5), int)
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [39]:
Z = np.tile(np.arange(5), (5,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def g():
    while True:
        yield np.random.randint(0,10)
np.fromiter(g(), int, 10)

array([4, 5, 5, 1, 6, 1, 6, 0, 5, 6])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
Z = np.linspace(0, 10, 11, endpoint=False)[1:]
print(Z)

[0.90909091 1.81818182 2.72727273 3.63636364 4.54545455 5.45454545
 6.36363636 7.27272727 8.18181818 9.09090909]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
rng = np.random.default_rng()
Z = rng.random(10)
Z.sort()
print(Z)

[0.04451858 0.08741116 0.26047566 0.3207427  0.48792843 0.54613205
 0.7605629  0.78242801 0.81611863 0.9854705 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
rng = np.random.default_rng()
A = rng.integers(10, size=(3,3))
B = rng.integers(10, size=(3,3))

In [45]:
equal = np.allclose(A, B)
print(equal)

False


In [46]:
equal = np.array_equal(A, B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [47]:
Z = np.arange(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [48]:
rng = np.random.default_rng(0)
Z = rng.integers(10, size=(10,2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
coordinate = np.column_stack((R,T))
print(coordinate)

[[10.          0.64350111]
 [ 5.38516481  0.38050638]
 [ 3.          0.        ]
 [ 0.          0.        ]
 [ 8.06225775  1.44644133]
 [10.81665383  0.98279372]
 [ 7.81024968  0.87605805]
 [11.40175425  0.66104317]
 [ 7.81024968  0.69473828]
 [10.29563014  1.06369782]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [49]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.76905614 0.39786448 0.97431619 0.29249295 0.8649169
 0.52220498 0.79444204 0.54088042 0.34689307]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [51]:
nx, ny = (5, 5)
x = np.linspace(0, 1, nx)
y = np.linspace(0, 1, ny)
xv, yv = np.meshgrid(x, y)
print(xv)
print(yv)

[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [58]:
X = np.tile(np.arange(8), (8, 1))
print(X)
Y = X - 1
print(Y)
C = (1 / (X - Y))
print(C)
print(np.linalg.det(C))

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]
[[-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]
 [-1  0  1  2  3  4  5  6]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
0.0


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [59]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [60]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [62]:
a = np.random.randint(10)
Z = np.arange(20)
index = np.abs(Z - a).argmin()
print(Z[index])

4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [65]:
Z = np.zeros(10, [('position', [('x', float, 1),
                                ('y', float, 1),
                                ('z', float, 1)]),
                  ('color', [('r', float, 1),
                              ('g', float, 1),
                              ('b', float, 1)])])
print(Z)

[((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))]


C:\Users\HP\AppData\Local\Temp\ipykernel_3612\1081909648.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', [('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [71]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (X-X.T)**2)
print(D)


[[0.         0.34273334 0.9042203  0.99199902 0.30517389 0.88937307
  1.11053472 1.09425008 0.25098582 0.06191875]
 [0.34273334 0.         0.56148696 0.64926568 0.03755945 0.54663972
  0.76780137 0.75151674 0.09174753 0.28081459]
 [0.9042203  0.56148696 0.         0.08777872 0.59904641 0.01484723
  0.20631442 0.19002978 0.65323448 0.84230155]
 [0.99199902 0.64926568 0.08777872 0.         0.68682513 0.10262596
  0.1185357  0.10225106 0.74101321 0.93008027]
 [0.30517389 0.03755945 0.59904641 0.68682513 0.         0.58419918
  0.80536083 0.78907619 0.05418807 0.24325514]
 [0.88937307 0.54663972 0.01484723 0.10262596 0.58419918 0.
  0.22116165 0.20487701 0.63838725 0.82745432]
 [1.11053472 0.76780137 0.20631442 0.1185357  0.80536083 0.22116165
  0.         0.01628464 0.8595489  1.04861597]
 [1.09425008 0.75151674 0.19002978 0.10225106 0.78907619 0.20487701
  0.01628464 0.         0.84326426 1.03233133]
 [0.25098582 0.09174753 0.65323448 0.74101321 0.05418807 0.63838725
  0.8595489  0.84326

In [72]:
import scipy
Z = np.random.random((10, 2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.23129659 0.86117669 0.93209867 0.80986404 0.43379662
  0.49859282 0.11858908 0.77359764 0.64642111]
 [0.23129659 0.         0.77751347 0.93346787 0.63054283 0.32187682
  0.51243783 0.24772442 0.65740454 0.62095301]
 [0.86117669 0.77751347 0.         0.34614675 0.40377595 0.45579907
  0.42060294 0.7526242  0.1587528  0.26477032]
 [0.93209867 0.93346787 0.34614675 0.         0.73830998 0.63916356
  0.43504748 0.81351147 0.48212408 0.3154328 ]
 [0.80986404 0.63054283 0.40377595 0.73830998 0.         0.39879359
  0.59013733 0.73897556 0.25626146 0.51740863]
 [0.43379662 0.32187682 0.45579907 0.63916356 0.39879359 0.
  0.27665232 0.34650581 0.34446244 0.32477932]
 [0.49859282 0.51243783 0.42060294 0.43504748 0.59013733 0.27665232
  0.         0.38027398 0.40754864 0.16247626]
 [0.11858908 0.24772442 0.7526242  0.81351147 0.73897556 0.34650581
  0.38027398 0.         0.67521501 0.53011618]
 [0.77359764 0.65740454 0.1587528  0.48212408 0.25626146 0.34446244
  0.40754864 0.67521

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [83]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
V = Z.view(np.int32)
print(V)

[87.84005  25.307205 61.926476 70.85197  96.13434  84.834526 81.910484
 62.667362 67.00419  44.350986]
[1118809627 1103787304 1115141302 1116582965 1119896776 1118415687
 1118032427 1115335521 1116078629 1110533993]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [87]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=',', dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [91]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)